version: "3"
services:
  authors-service:
    build:
      context: ./authors-service
    ports:
      - 8081:8081

  books-service:
    build:
      context: ./books-service
    ports:
      - 8082:8082
    environment:
      AUTHORS_URL: http://authors-service:8081

  bff-service:
    build:
      context: ./bff-service
    ports:
      - 8083:8083
    environment:
      AUTHORS_URL: http://authors-service:8081
      BOOKS_URL: http://books-service:8082