version: "3"
services:
  authors-service:
    build:
      context: ./authors-service
    ports:
      - 8081:8081

  books-service:
    build:
      context: ./books-service
    ports:
      - 8082:8082
    environment:
      AUTHORS_URL: http://authors-service:8081
      AUTHORS_GRPC_HOST: authors-service
      AUTHORS_GRPC_PORT: 50051

  bff-service:
    build:
      context: ./bff-service
    ports:
      - 8083:8083
    environment:
      AUTHORS_URL: http://authors-service:8081
      BOOKS_URL: http://books-service:8082
      AUTHORS_GRPC_HOST: authors-service
      AUTHORS_GRPC_PORT: 50051
      BOOKS_GRPC_HOST: books-service
      BOOKS_GRPC_PORT: 50052